# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgrabung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bearbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Befund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('deutung', models.CharField(max_length=50)),
                ('datierung', models.CharField(max_length=50)),
                ('kurzbeschreibung', models.TextField(max_length=250)),
                ('datum', models.DateField()),
                ('planum', models.CharField(max_length=20)),
                ('ausgrabung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Ausgrabung')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('richtung', models.CharField(max_length=50)),
                ('datum', models.DateField()),
                ('befund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Befund')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('richtung', models.CharField(max_length=50)),
                ('datum', models.DateField()),
                ('befund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavation.Befund')),
            ],
        ),
    ]
