# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0004_auto_20160827_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='befund',
            name='masse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='befund',
            name='datierung',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
