# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0006_befund_bearbeiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='bearbeiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Bearbeiter'),
        ),
        migrations.AddField(
            model_name='profil',
            name='bearbeiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Bearbeiter'),
        ),
        migrations.RemoveField(
            model_name='foto',
            name='befund',
        ),
        migrations.AddField(
            model_name='foto',
            name='befund',
            field=models.ManyToManyField(to='excavation.Befund'),
        ),
    ]
