# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0007_auto_20160827_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='befund',
        ),
        migrations.AddField(
            model_name='profil',
            name='befund',
            field=models.ManyToManyField(to='excavation.Befund'),
        ),
    ]
