# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0009_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='befund',
            name='nummer',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='nummer',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='grabung',
            name='nummer',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nummer',
            field=models.IntegerField(unique=True),
        ),
    ]
