# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0010_auto_20160827_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='befund',
            name='planum',
        ),
        migrations.AddField(
            model_name='befund',
            name='bemerkung',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='bemerkung',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='planum',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profil',
            name='bemerkung',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
