# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0012_auto_20160827_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='befund',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
