# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0013_auto_20160827_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabBeschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beschreibung', models.TextField()),
                ('erhaltung', models.CharField(max_length=50)),
                ('bestattung', models.CharField(max_length=50)),
                ('lage', models.CharField(max_length=50)),
                ('schaedel', models.CharField(max_length=50)),
                ('armhaltung', models.CharField(max_length=50)),
                ('bearbeiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Bearbeiter')),
                ('foto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Foto')),
            ],
        ),
    ]
