# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0014_grabbeschreibung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grabbeschreibung',
            old_name='Beschreibung',
            new_name='beschreibung',
        ),
    ]
