# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excavation', '0015_auto_20160915_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabbeschreibung',
            name='befund',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='excavation.Befund'),
        ),
    ]
